// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlfMFAg29Va857baF-oG9CAEkeQEQZR4',
    appId: '1:371845310539:android:543dfaad84ff1d0a7b85ce',
    messagingSenderId: '371845310539',
    projectId: 'recipe-app-e163c',
    storageBucket: 'recipe-app-e163c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpLgXj4mSNwFIzXFy0XCpACisVF3AipM',
    appId: '1:371845310539:web:4989db4e359a10517b85ce',
    messagingSenderId: '371845310539',
    projectId: 'recipe-app-e163c',
    authDomain: 'recipe-app-e163c.firebaseapp.com',
    storageBucket: 'recipe-app-e163c.firebasestorage.app',
    measurementId: 'G-L3W9LXWMX0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTGz9fVkH1icwbf0JsbgDNpDJNRJNFz0',
    appId: '1:371845310539:ios:76eddbe90f40a6697b85ce',
    messagingSenderId: '371845310539',
    projectId: 'recipe-app-e163c',
    storageBucket: 'recipe-app-e163c.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTGz9fVkH1icwbf0JsbgDNpDJNRJNFz0',
    appId: '1:371845310539:ios:98fd9616d734567a7b85ce',
    messagingSenderId: '371845310539',
    projectId: 'recipe-app-e163c',
    storageBucket: 'recipe-app-e163c.firebasestorage.app',
    iosBundleId: 'com.emrecanturk.recipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTpLgXj4mSNwFIzXFy0XCpACisVF3AipM',
    appId: '1:371845310539:web:14f15bcc6f27a5ee7b85ce',
    messagingSenderId: '371845310539',
    projectId: 'recipe-app-e163c',
    authDomain: 'recipe-app-e163c.firebaseapp.com',
    storageBucket: 'recipe-app-e163c.firebasestorage.app',
    measurementId: 'G-7EG0WSQ75T',
  );

}